"use client";

interface AIHooksProps {
  hooks: string[];
  productId: string;
}

export function AIHooks({ hooks, productId }: AIHooksProps) {
  if (!hooks || hooks.length === 0) return null;

  return (
    <div className="mt-8">
      <div className="flex items-center gap-2 mb-3">
        <svg
          className="w-4 h-4 text-mocha-400"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
          />
        </svg>
        <span className="text-micro text-ivory-400 font-mono uppercase tracking-wider">
          AI Insights
        </span>
      </div>

      <div className="flex flex-wrap gap-2">
        {hooks.map((hook, index) => (
          <span
            key={`${productId}-hook-${index}`}
            className="inline-flex items-center px-3 py-1.5 bg-mocha-500/15 text-mocha-400 text-sm font-mono border border-mocha-500/20 hover:bg-mocha-500/25 transition-colors cursor-default"
          >
            {hook}
          </span>
        ))}
      </div>

      {/* AI confidence note */}
      <p className="mt-4 text-micro text-ivory-400/60 font-mono">
        Generated by GPT-4o Vision analysis
      </p>
    </div>
  );
}
